### ISSUE TITLE
Top level statements

### ISSUE THREAD

**Issue by KeterSCP** [dotnetprojects/MonacoRoslynCompletionProvider#15]
Currently, when you try to write some top-level statements in the editor, you will get an error

![image](https://github.com/dotnetprojects/MonacoRoslynCompletionProvider/assets/38229504/d5da76d3-1b60-4aff-95c2-355897cdc8a9)

This is due to project being compiled as DLL and not an EXE [here](https://github.com/dotnetprojects/MonacoRoslynCompletionProvider/blob/d2ff2fa85e8c7825da4ee94337265342bb533d82/MonacoRoslynCompletionProvider/MonacoRoslynCompletionProvider/CompletionWorkspace.cs#L78)

**Comment by jogibear9988** [comment]
yeah, caus this will not work in our case. But I'll look to add an option, when I've time

**Comment by jogibear9988** [comment]
maybe yyou could create a pull request?

**Comment by KeterSCP** [comment]
Sure, I'll take a look
